# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('franchise_series', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=25)),
                ('year', models.IntegerField(null=True)),
                ('franchise_year', models.IntegerField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('season_title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=False)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_web_app.Division')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_web_app.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='divisions',
            field=models.ManyToManyField(through='de_web_app.PropertyDivision', to='de_web_app.Division'),
        ),
        migrations.AddField(
            model_name='asset',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_web_app.Property'),
        ),
    ]
