# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de_web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydivision',
            name='included',
        ),
    ]
